project_id = "edqjskmaorvfxluojsth"

[functions.send-waitlist-notification]
verify_jwt = false

[functions.send-community-notification]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = true

[functions.send-contact-notification]
verify_jwt = true

[functions.send-teardown-notification]
verify_jwt = true

[functions.send-invite-request]
verify_jwt = false
